web:
  build: .
  ports:
    - "80:3000"
  volumes:
    - .:/usr/src/app/:rw
  links:
    - db
  environment:
    - NODE_ENV=dev
  command: >
    sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists &&
        npm rebuild node-sass;
      else
        npm install;
      fi &&
      webpack &&
      /usr/local/bin/node ./server/server.js;
    '
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=dev
    - POSTGRES_USER=dev
    - POSTGRES_DB=miniShop
  volumes:
    - ./data:/data